INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (1,'ACCOUNT_ACCESS','계정_접근');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (2,'ACCOUNT_MANAGE','계정_관리');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (3,'BOARD_MANAGE','게시판_관리');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (4,'FILE_ACCESS','파일_접근');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (5,'FILE_MANAGE','파일_관리');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (6,'TAG_ACCESS','태그_접근');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (7,'TAG_MANAGE','태그_관리');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (8,'SEARCH_ACCESS','검색_접근');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (9,'JOB_ACCESS','취업_접근');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (10,'JOB_MANAGE','취업_관리');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (11,'STATICS_MANAGE','통계_관리');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (12,'ACCESS_MANAGE','접근_관리');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (13,'CAREER_ACCESS','이력_접근');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (14,'CAREER_MANAGE','이력_관리');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (15,'REPORT_ACCESS','신고_접근');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (16,'REPORT_MANAGE','신고_관리');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (17,'AUTHORITY_MANAGE','권한_관리');
INSERT INTO AUTHORITY (AUTHORITY_ID, NAME_ENG, NAME_KOR) VALUES (18,'SCHEDULE_MANAGE','시간표_관리');


INSERT INTO AUTHORITY_GROUP (AUTHORITY_GROUP_ID, DESCRIPTION, NAME) VALUES (1,'비로그인 사용자','DEFAULT');

INSERT INTO AUTHORITY_GROUP_AUTHORITY_MAPPING (AUTHORITY_GROUP_AUTHORITY_MAPPING_ID, AUTHORITY_ID, AUTHORITY_GROUP_ID) VALUES (1,1,1);
INSERT INTO AUTHORITY_GROUP_AUTHORITY_MAPPING (AUTHORITY_GROUP_AUTHORITY_MAPPING_ID, AUTHORITY_ID, AUTHORITY_GROUP_ID) VALUES (2,4,1);
INSERT INTO AUTHORITY_GROUP_AUTHORITY_MAPPING (AUTHORITY_GROUP_AUTHORITY_MAPPING_ID, AUTHORITY_ID, AUTHORITY_GROUP_ID) VALUES (3,8,1);
