package com.se.apiserver.v1.timetable.domain.entity;

public enum TimeTableStatus {
  CREATION, SELECT_LECTURE_ROOM, SELECT_TEACHER, SELECT_SUBJECT, INSERT_LECTURE_UNABLE_TIME,
  INSERT_OPEN_SUBJECT, INSERT_LIBERAL_ARTS, PLACE_SUBJECT, FINAL_REVIEW, FINISHED
}
